### ISSUE TITLE
23rd-aug-16-iphone-update-breaks-button-widget-node-red-contrib-blynk-websockets

### ISSUE THREAD

**Issue by Toshibass** [tzapu/node-red-contrib-blynk-websockets#11]
Hi Tzapu, don't know if you have seen my post on blynk community site, was wondering if you see this issue as well, do you think its a blynk-websockets problem or a blynk problem ?

Simple to reproduce see attached ... button is set as push not switch .... press the button and result is 1 followed immediately by 0  then on release of button nothing.

Prior to update same same set up button returned 1 on push 0 when released as per blynk documentation.
![capture](https://cloud.githubusercontent.com/assets/6310911/17961124/cbd101f4-6aa1-11e6-8820-7ef52e05c30d.JPG)

**Comment by Toshibass** [comment]
OK I got a reply from blynk community site, they say it been like this for months (bull s**t) anyway he says 1 or 2 weeks it will be fixed lets see.

**Comment by tzapu** [comment]
cool, glad you fot somewhere with them. i ve noticed some modifications on how buttons behave in the last updates in relation to the highlight. quite possibly they introduced this when they added those changes.

on my local server, buttons seem fine 1/0 but if you call them through the http api with 1, they behave like a switch, you need to also issue a 0 through http

good luck

**Comment by Toshibass** [comment]
Thanks for your response, I know for sure this change came with the latest update... I have always updated each and every ios update, I told you before I made a combination lock screen, it has 9 "push" buttons which have to be pressed in the right combination or no other button works in my project, it worked perfectly until the latest update, anyway enough crying .. I'm on vacation from tomorrow for 2 weeks so I can chill.

**Comment by tzapu** [comment]
have a good one :)
