### ISSUE TITLE
Websockets not working after recent update

### ISSUE THREAD

**Issue by lyte99** [tzapu/node-red-contrib-blynk-websockets#13]
Hello,

After using these nodes successfully for some time, I updated my raspbian via the normal apt-get update path and now the websockets will not connect to any server, local or cloud.  I've tried this on two machines and got the same results.  The console shows error then close over and over again connecting to both the cloud and local servers.

I'm currently using node 0.10.29 and node-red 0.15.2.  I also tried updating to node 4.7 and got the same results.

**Comment by cdfairchild** [comment]
Hi lyte99,

I too am having trouble connecting to the websocket URL ws://blynk-cloud.com:8082/websocket.  At first I thought it might be my node-red setup, but these connections also fail when trying to reach them via a standard websocket echo test such as http://websocket.org/echo.html.  I'm thinking the server address and/or ports have changed again.  Hopefully Alex will have some insight.

**Comment by shtirlic** [comment]
try `ws://blynk-cloud.com:8082/websockets` look to the  `s` on the end

**Comment by lyte99** [comment]
@shtirlic That did fix my issue, thank you.  @cdfairchild any luck?

**Comment by cdfairchild** [comment]
I'm in the process of rebuilding my node-red server and haven't tried.  But I hope to get to it this week.  Thanks!
