### ISSUE TITLE
128 virtual pins ?

### ISSUE THREAD

**Issue by Toshibass** [tzapu/node-red-contrib-blynk-websockets#5]
Hi Tzapu is there a easy fix to access virtual pins 65 to 127 that are now available with the latest blynk update on both android and ios platforms ?

**Comment by tzapu** [comment]
HI Toshi,

I ll try and make a quick update tomorrow

Cheers
Alex

**Comment by tzapu** [comment]
hi, sent an update, let me know if it s ok as i did not get to test
cheers

**Comment by Toshibass** [comment]
Superb I tested latest update to node-red-contrib-blynk-websockets which adds support for 128 virtual pins and it works great, hearing that support for SSL will also be available soon is fantastic news.
