### ISSUE TITLE
websockets and Digital Pin support

### ISSUE THREAD

**Issue by scropion86** [tzapu/node-red-contrib-blynk-websockets#6]
hi Alex,

in resetfull API i can control any Digital - D - Pin or Virtual - V - Pin , but in your Node only virtual
Pin can be communicated , i know that in sketch this can be solved very easily.
but is this a limitation of your Node or Blynk Websockets API.

thanks

**Comment by tzapu** [comment]
hi, node red acts as a hardware device, and uses the API Blynk provided to connect as a device.

because of that, it can't really switch digital pins as it doesn't know of any.

it might be possible through a bridge widget, but i did not look into that at all, so don t know what to tell you.

**Comment by scropion86** [comment]
thanks Alex.
it's fine now we have 128 V pin so no issue , and throw sketch this can be solved.
